name: Publish Docker

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get release version
        id: get_version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_SHA:0:10})
      - name: Publish PHP Image to Registry
        id: dockerphp
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tonysm/docker4laravelapp-php
          dockerfile: .docker/php/prod.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
          cache: ${{ github.event_name != 'schedule' }}
      - name: Publish Nginx Image to Registry
        id: dockernginx
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: tonysm/docker4laravelapp-nginx
          dockerfile: .docker/nginx/prod.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest,${{ env.RELEASE_VERSION }}"
          cache: ${{ github.event_name != 'schedule' }}
      - name: Patch Infrastructure Manifests
        run: |
          echo "Published image tag: ${RELEASE_VERSION}"
